name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        experimental: [false]
        include:
          - rust: nightly
            experimental: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Rust
      run: rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt clippy

    - name: Setup
      run: |
        rustup default ${{ matrix.rust }}
        toolchain=$(rustup default)
        echo "Use Rust toolchain: $toolchain"
        rustc --version
        cargo --version

    - name: Build
      run: cargo build --verbose

    - name: Format check
      run: cargo fmt --all -- --check

    - name: Clippy check
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test -- --nocapture
